# Generated by Django 3.0.2 on 2020-03-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='pics/')),
                ('Date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singer_name', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('musicfile', models.FileField(upload_to='music/')),
            ],
        ),
    ]
