# Generated by Django 3.0.2 on 2020-03-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='img',
            field=models.ImageField(blank='True', upload_to='pics/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='music',
            name='date',
            field=models.DateField(),
        ),
    ]
