# Generated by Django 3.0.2 on 2020-03-20 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_counts', models.PositiveIntegerField(default=1)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
            ],
        ),
    ]
