# Generated by Django 2.2 on 2020-03-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_download'),
    ]

    operations = [
        migrations.DeleteModel(
            name='download',
        ),
    ]
